baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Pascal Grittmann"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[[menus.main]]
name = 'Bio'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Publications'
pageRef = '/publications'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'Tools'
pageRef = '/tools'
weight = 40

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 500