baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Bio'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Publications'
pageRef = '/publications'
weight = 20

[[menus.main]]
name = 'Learning materials'
pageRef = '/learning'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
