baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Bio'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Publications'
pageRef = '/publications'
weight = 20

[[menus.main]]
name = 'Tools'
pageRef = '/tools'
weight = 30

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
